cadastre/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from data.views import LoginUserView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/login/', LoginUserView.as_view(), name='login'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('data.urls')),
]

urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

data/urls.py
from django.urls import path

from .views import (
    HomeView,
    
    ReadParcelsView,
    WritenParcelsView,

    ReadControlsView,
    WritenControlsView,

    SignUpView,
    UserProfileView,

    OwnersListView,

    SearchView,

    ParcelDetailView,
    # ControlDetailView,

)

app_name = 'data'


urlpatterns = [
    path('', HomeView.as_view(), name='home_page'),
    
    path('parcels/', ReadParcelsView.as_view(), name='read_parcels_page'),
    path('writen-parcels/', WritenParcelsView.as_view(), name='writen_parcels_page'),

    path('controls/', ReadControlsView.as_view(), name='read_controls_page'),
    path('writen-controls/', WritenControlsView.as_view(), name='writen_controls_page'),

    path('parcel-owners/', OwnersListView.as_view(), name='owners_page'),

    path('sign-up/', SignUpView.as_view(), name='user_signup_page'),
    path('profile/', UserProfileView.as_view(), name='user_profile_page'),

    path('search', SearchView.as_view(), name='search_page'),

    path('parcel/<str:pk>/', ParcelDetailView.as_view(), name='parcel_page')
    # path('control/<int:pk>/', ControlDetailView.as_view(), name='control_page'),
]

data/models.py
import uuid

from .utils import HOLDTYPE, LANDUSE
from .manager import CustomUserManager

from django.contrib.gis.db import models
from django.utils.translation import gettext_lazy as _
from django.urls import reverse
from django.contrib.auth.models import AbstractUser
from django.utils.text import slugify


class User(AbstractUser):
    id = models.UUIDField(primary_key=True, unique=True, default=uuid.uuid4)
    email = models.EmailField(_('email address'), unique=True)
    full_name = models.CharField(_('full name'), max_length=125, unique=True)
    date_joined = models.DateTimeField(auto_now_add=True) # saved automatically when creating an object
    date_updated = models.DateTimeField(auto_now=True) # updated automatically when saving an object
    thumbnail_img  = models.ImageField(
        upload_to='users_logos',
        default='default_avatar.png' # Img in media
    )

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['full_name']

    username = None
    first_name = None
    last_name = None

    objects = CustomUserManager()

    def __str__(self):
        return (f'{self.full_name}')
        

class LandOwner(models.Model):
    id = models.UUIDField(primary_key=True, unique=True, editable=True, default=uuid.uuid4)
    user = models.OneToOneField(User, related_name='land_owner_user', on_delete=models.CASCADE)

    def __str__(self):
        return self.user.full_name



class LandUse(models.Model):
    id = models.UUIDField(primary_key=True, unique=True, editable=True, default=uuid.uuid4)
    name = models.CharField(_('type of land use'), unique=True, max_length=125, choices=LANDUSE.choices)
    land_rent = models.FloatField(default=0)
    description = models.CharField(_('decription of landuse type'), max_length=225)

    def __str__(self):
        return self.name


# Parcel model.
class Parcel(models.Model):
    id = models.CharField(max_length=200, primary_key=True, unique=True, editable=False)
    parcel_number = models.CharField(max_length=50)
    fr_datum = models.CharField(max_length=50, null=True, blank=True)
    county = models.CharField(max_length=125)
    sub_county = models.CharField(max_length=125)
    owners = models.ManyToManyField(LandOwner, related_name='owner_parcels', verbose_name=_('the people to which the parcel belong'), blank=True)
    land_use = models.ForeignKey(LandUse, related_name='landuse_parcels', on_delete=models.CASCADE, null=True, blank=True)
    hold_type = models.CharField(max_length=125, choices=HOLDTYPE.choices, default=HOLDTYPE.FREEHOLD)
    date_created = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        if not self.id:
            if not self.county:
                raise ValueError(_('County name required'))
            if not self.parcel_number:
                raise ValueError(_('Parcel number name required'))
                
            self.id = slugify('%s %s' % (self.county,self.parcel_number))

        super(Parcel, self).save(*args, **kwargs)

    class Meta:
        ordering = ["-date_created"]
        constraints = [
            models.UniqueConstraint(fields=['parcel_number', 'county'], name='unique_id')
        ]
    
    def __str__(self):
        return self.parcel_number

    def get_absolute_url(self):
        return reverse('data:parcel_page', kwargs={'pk' : self.id})
    


# Zone37SParcel model.
class Zone37SParcel(models.Model):
    id = models.UUIDField(primary_key=True, unique=True, editable=True, default=uuid.uuid4)
    parcel = models.OneToOneField(Parcel, related_name='zone_37s_parcel', on_delete=models.CASCADE)
    geom = models.MultiPolygonField(srid=21037)

    def __str__(self):
        return self.parcel.parcel_number


class Zone37NParcel(models.Model):
    id = models.UUIDField(primary_key=True, unique=True, editable=True, default=uuid.uuid4)
    parcel = models.OneToOneField(Parcel, related_name='zone_37n_parcel', on_delete=models.CASCADE)
    geom = models.MultiPolygonField(srid=21096)
    

class Zone36SParcel(models.Model):
    id = models.UUIDField(primary_key=True, unique=True, editable=True, default=uuid.uuid4)
    parcel = models.OneToOneField(Parcel, related_name='zone_36s_parcel', on_delete=models.CASCADE)
    geom = models.MultiPolygonField(srid=21097)


class Zone36NParcel(models.Model):
    id = models.UUIDField(primary_key=True, unique=True, editable=True, default=uuid.uuid4)
    parcel = models.OneToOneField(Parcel, related_name='zone_36n_parcel', on_delete=models.CASCADE)
    geom = models.MultiPolygonField(srid=21036)


# Parcel Beacons model.
class ParcelBeacon(models.Model):
    id = models.UUIDField(primary_key=True, unique=True, editable=True, default=uuid.uuid4)
    name = models.CharField(_('station name'), max_length=20)
    parcels = models.ManyToManyField(Parcel, related_name='parcel_beacons', blank=True)

    def __str__(self):
        return self.name

    # def get_absolute_url(self):
    #     return reverse('data:control_page', kwargs={'pk' : self.id})
    

class Zone37SBeacon(models.Model):
    id = models.UUIDField(primary_key=True, unique=True, editable=True, default=uuid.uuid4)
    beacon = models.OneToOneField(ParcelBeacon, related_name='zone_37s_beacon', on_delete=models.CASCADE)
    geom = models.MultiPointField(srid=21037)


class Zone37NBeacon(models.Model):
    id = models.UUIDField(primary_key=True, unique=True, editable=True, default=uuid.uuid4)
    beacon = models.OneToOneField(ParcelBeacon, related_name='zone_37n_beacon', on_delete=models.CASCADE)
    geom = models.MultiPointField(srid=21096)
    

class Zone36SBeacon(models.Model):
    id = models.UUIDField(primary_key=True, unique=True, editable=True, default=uuid.uuid4)
    beacon = models.OneToOneField(ParcelBeacon, related_name='zone_36s_beacon', on_delete=models.CASCADE)
    geom = models.MultiPointField(srid=21097)
    

class Zone36NBeacon(models.Model):
    id = models.UUIDField(primary_key=True, unique=True, editable=True, default=uuid.uuid4)
    beacon = models.OneToOneField(ParcelBeacon, related_name='zone_36n_beacon', on_delete=models.CASCADE)
    geom = models.MultiPointField(srid=21036)

data/views.py
import json

from django.db.models import Q

from django.core.serializers import serialize

from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic.edit import (
    FormView,
)

from django.contrib.gis.geos import GEOSGeometry, MultiPolygon, Polygon, Point, MultiPoint
from django.db import transaction
from django.contrib import messages

from django.views.generic import (
    TemplateView,
    ListView,
    DetailView
)

from django.contrib.auth.mixins import (
    LoginRequiredMixin,
)

from django.contrib.auth.views import (
    LoginView,
)


from .forms import (
    ParcelsShapefileForm,
    ControlsShapefileForm,
    ApproveShapefileForm,
    UserSignupModelForm,
    UserLoginForm,
    ExploreForm,
)


import pandas as pd
import geopandas as gpd

from shapely import wkt


from .models import (
    Parcel,
    Zone37SParcel,
    Zone37NParcel,
    Zone36SParcel,
    Zone36NParcel,
    ParcelBeacon,
    Zone37SBeacon,
    Zone37NBeacon,
    Zone36SBeacon,
    Zone36NBeacon,
    LandOwner,
)

def get_all_controls_geojson():

    if Zone37SBeacon.objects.exists() and ParcelBeacon.objects.exists():
        controls_with_geom = json.loads(serialize('geojson', Zone37SBeacon.objects.select_related('beacon')))
        controls_with_attrs = json.loads(serialize('json', ParcelBeacon.objects.all()))
        for control_geom in controls_with_geom['features']:
            control_geom_id = control_geom['properties']['beacon']
            for control_attr in controls_with_attrs:
                control_attr_id = control_attr['pk']

                if control_geom_id == control_attr_id:
                    control_geom['properties'].update(control_attr['fields'])
        
        controls_geojson = json.dumps(controls_with_geom)
        return controls_geojson


def get_all_parcels_geojson():

    if Zone37SParcel.objects.exists() and Parcel.objects.exists():
        parcels_with_geom = json.loads(serialize('geojson', Zone37SParcel.objects.select_related('parcel')))
        parcels_with_attrs = json.loads(serialize('json', Parcel.objects.all()))
        for parcel_geom in parcels_with_geom['features']:
            parcel_geom_id = parcel_geom['properties']['parcel']
            for parcel_attr in parcels_with_attrs:
                parcel_attr_id = parcel_attr['pk']

                if parcel_geom_id == parcel_attr_id:
                    parcel_geom['properties'].update(parcel_attr['fields'])
        
        parcels_geojson = json.dumps(parcels_with_geom)
        return parcels_geojson


class HomeView(TemplateView):
    template_name = 'data/homepage.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'page_title':'HOME',
        })
        return context


class ReadParcelsView(FormView):
    template_name = 'data/parcels_write.html'
    form_class = ParcelsShapefileForm
    success_url = reverse_lazy('data:home_page')

    # from ContextMixin via FormMixin
    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['parcels_upload_form'] = data.get('form')
        data['existing_parcels_geojson'] = get_all_parcels_geojson()
        return data

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            shapefile_data = form.cleaned_data.get('shapefile')
            shapefile_attributes = shapefile_data.get('shapefile_data')
            crs = shapefile_data.get('crs')

            if shapefile_attributes and crs:
                shapefile_data_df = pd.DataFrame(data=shapefile_attributes)
                shapefile_data_df['geometry'] = shapefile_data_df['geometry'].apply(wkt.loads)

                shapefile_gdf = gpd.GeoDataFrame(shapefile_data_df, geometry='geometry')
                shapefile_gdf.set_crs(crs, allow_override=True, inplace=True)
                shapefile_gdf.set_index('parcel_num', inplace=True)
                
                
                with transaction.atomic():

                    written_parcels = []

                    for parcel_number in shapefile_gdf.index.values.tolist():

                        try:
                            geom = GEOSGeometry(shapefile_gdf.at[parcel_number, 'geometry'].wkt, srid=request.session.get('crs'))
                        except Exception:
                            continue
                        
                        if isinstance(geom, Polygon):
                            geom = MultiPolygon(geom)

                        parcel,_ = Parcel.objects.update_or_create(
                            parcel_number=parcel_number,
                            defaults={
                                'fr_datum': shapefile_gdf.at[parcel_number, 'fr_datum'],
                                'county': shapefile_gdf.at[parcel_number, 'county'],
                                'sub_county': shapefile_gdf.at[parcel_number, 'sub_county'],
                            },
                        )

                        if crs == 21037:
                            geom_parcel,_ = Zone37SParcel.objects.update_or_create(
                                parcel=parcel,
                                defaults={'geom':geom}
                            )
                            written_parcels.append(str(geom_parcel.id))
                        elif crs == 21096:
                            geom_parcel,_ = Zone37NParcel.objects.update_or_create(
                                parcel=parcel,
                                defaults={'geom':geom}
                            )
                            written_parcels.append(str(geom_parcel.id))
                        elif crs == 21097:
                            geom_parcel,_ = Zone36SParcel.objects.update_or_create(
                                parcel=parcel,
                                defaults={'geom':geom}
                            )
                            written_parcels.append(str(geom_parcel.id))
                        elif crs == 21036:
                            geom_parcel,_ = Zone36NParcel.objects.update_or_create(
                                parcel=parcel,
                                defaults={'geom':geom}
                            )
                            written_parcels.append(str(geom_parcel.id))

                    request.session.update({'created_parcels':written_parcels})
                    messages.info(request, 'Parcels saved successfully')
                    return redirect('data:writen_parcels_page')
                            

        return self.form_invalid(form)


class WritenParcelsView(FormView):
    
    template_name = 'data/written_parcels.html'
    form_class = ApproveShapefileForm
    success_url = reverse_lazy('data:home_page')
    

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['approve_parcels_form'] = self.get_form()
        return data
        
    def get(self, request, *args, **kwargs):

        if not request.session.get('created_parcels'):
            return redirect('data:home_page')

        context = self.get_context_data()
        zone_parcels_data = []

        created_parcels = Zone37SParcel.objects.filter(Q(id__in=request.session.get('created_parcels')))
        if created_parcels:
            for parcel in created_parcels:
                parcel_obj = Parcel.objects.filter(Q(zone_37s_parcel=parcel))
                zone_parcel_data = json.loads(serialize('json', parcel_obj))
                zone_parcels_data.append(zone_parcel_data[0])

        if not created_parcels:
            created_parcels = Zone37NParcel.objects.filter(Q(id__in=request.session.get('created_parcels')))
            if created_parcels:
                for parcel in created_parcels:
                    parcel_obj = Parcel.objects.filter(Q(zone_37n_parcel=parcel))
                    zone_parcel_data = json.loads(serialize('json', parcel_obj))
                    zone_parcels_data.append(zone_parcel_data[0])

        if not created_parcels:
            created_parcels = Zone36SParcel.objects.filter(Q(id__in=request.session.get('created_parcels')))
            if created_parcels:
                for parcel in created_parcels:
                    parcel_obj = Parcel.objects.filter(Q(zone_36s_parcel=parcel))
                    zone_parcel_data = json.loads(serialize('json', parcel_obj))
                    zone_parcels_data.append(zone_parcel_data[0])

        if not created_parcels:
            created_parcels = Zone36NParcel.objects.filter(Q(id__in=request.session.get('created_parcels')))
            if created_parcels:
                for parcel in created_parcels:
                    parcel_obj = Parcel.objects.filter(Q(zone_36n_parcel=parcel))
                    zone_parcel_data = json.loads(serialize('json', parcel_obj))
                    zone_parcels_data.append(zone_parcel_data[0])


        if created_parcels and zone_parcels_data:
            parcels_data = json.loads(serialize('geojson', created_parcels))
            for parcel in parcels_data['features']:
                parcel_id = parcel['properties']['parcel']
                for zone_parcel in zone_parcels_data:
                    zone_parcel_id = zone_parcel['pk']

                    if parcel_id == zone_parcel_id:
                        parcel['properties'].update(zone_parcel['fields'])


            context.update({
                'parcels_geojson':json.dumps(parcels_data)
            })
            del request.session['created_parcels']
            
        return self.render_to_response(context)

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            value = form.cleaned_data.get('approve')
            if value == 'Discard':
                pass
            
            return self.form_valid(form)
            

data/templates/data/controls_write.html
{% extends 'base.html' %}
{% load static %}

{% block meta_assets %}
    
{% endblock %}

{% block content %}
{% include 'main_nav.html' %}

<link rel="stylesheet" href="{% static 'css/open_layers_css.css' %}" />


<style>
    #shapefile_preview_map{width:100%;height:520px;}
</style>

<div class="p-4 my-4 bg-white">

    <div class="shadow-sm py-4 px-2 mb-4 bg-white">

        {% if existing_controls_geojson %}
        <p class="h5 text-success mb-3">Existing Beacons</p>

        <div class="row">
            <div class="col-md-9">
              <div id="shapefile_preview_map"></div>
            </div>
            <div class="col bg-light">
              <div id="detail_content" class="p-2"></div>
            </div>
          </div>

            <script>
                const existing_controls_geojson = '{{ existing_controls_geojson|escapejs }}'
            </script>

          <script src="{% static 'data/js/existing_controls_map.js' %}"></script>
          {% else %}

          <p class="h5 text-dark mb-2">No Existing Beacons</p>

          {% endif %}
    </div>

    <form action="" method="post" enctype="multipart/form-data">
        <div class="shadow-sm py-4 px-2 mb-4 bg-white">
            <p class="py-3">Upload shapefile for updating database records</p>

            <div class="table-responsive">
                <table class="table table-light">
                    
                    {% csrf_token %}
                    {{ controls_upload_form.as_table }}
                        
                </table>
            </div>

            <div class="my-2">
                <button type='submit' id="read_data_btn" class="btn btn-outline-success">
                    Upload
                </button>
            </div>
        </div>
    </form>
    
</div>


{% endblock %}

data/templates/data/homepage.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

{% block content %}


<p class="h1 text-center py-5 rubik-light-font" id="main_title">
    Land Administration Domain Model (LADM)
</p>


{% include 'main_nav.html' %}


<div id="" class="bg-light rounded-3">

    <div class="my-4 px-5 pt-5">
        <p class="h4">LADM, Data and Linked Systems</p>
    </div>

    <div class="px-5 py-4">
        <p class="h5">Site Functions:</p>

        <ul class="list-group list-group-flush">
            <li class="list-group-item">Website access by system users</li>
            <li class="list-group-item">Navigation to site pages for parcels, beacons data</li>
            <li class="list-group-item">Linked data principles for website interactions</li>
            <li class="list-group-item">Data updation, addition and deletion by permitted staff</li>
        </ul>
    </div>
</div>

<div class="my-5 px-5 py-4 bg-light rounded-3">
    <p class="h5 mb-5">Data Statistics</p>
    <div class="accordion" id="stats_accordion">

        <div class="accordion-item">
            <h2 class="accordion-header" id="location">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#parcel_location" aria-expanded="true" aria-controls="parcel_location">
                  Parcels by County
                </button>
            </h2>
            <div id="parcel_location" class="accordion-collapse collapse" aria-labelledby="location" data-bs-parent="#stats_accordion">
                <div class="accordion-body">
                    <div class="row">
                        <div class="col-sm bg-light p-4 rounded">
                            <p class="font-montserrat-medium text-prim-color">
                                Parcels by county
                            </p>
                            <p class="font-montserrat-regular text-prim-color">
                                The {{ num_surveyors|apnumber }} surveyor{{ num_surveyors|pluralize }} have their respective career specializations represented as shown in the graph alongside.
                            </p>
                        </div>
                        <div class="col-sm d-flex justify-content-center">
                            {{ surveyors_div|safe }}
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="accordion-item">
            <h2 class="accordion-header" id="landuse">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#parcel_landuse" aria-expanded="false" aria-controls="parcel_landuse">
                  Parcels by Landuse
                </button>
            </h2>
            <div id="parcel_landuse" class="accordion-collapse collapse" aria-labelledby="landuse" data-bs-parent="#stats_accordion">
                <div class="accordion-body">
                    <div class="row">
                        <div class="col-sm d-flex justify-content-center">
                            {{ parcels_div|safe }}
                        </div>
                        <div class="col-sm bg-light p-4 rounded">
                            <p class="font-montserrat-medium text-prim-color">Parcels by landuse</p>
                            <p class="font-montserrat-regular text-prim-color">
                                The {{ num_parcels|apnumber }} parcel{{ num_parcels|pluralize }} have hold types as shown in the graph alongside.
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="accordion-item">
            <h2 class="accordion-header" id="holdtype">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#parcel_holdtype" aria-expanded="false" aria-controls="parcel_holdtype">
                  Parcels by Holdtype
                </button>
            </h2>
            <div id="parcel_holdtype" class="accordion-collapse collapse" aria-labelledby="holdtype" data-bs-parent="#stats_accordion">
                <div class="accordion-body">
                    <div class="row">
                        
                        <div class="col-sm bg-light p-4 rounded">
                            <p class="font-montserrat-medium text-prim-color">Parcels by holdtype</p>
                            <p class="font-montserrat-regular text-prim-color">
                                The {{ num_parcels|apnumber }} parcel{{ num_parcels|pluralize }} have hold types as shown in the graph alongside.
                            </p>
                        </div>

                        <div class="col-sm d-flex justify-content-center">
                            {{ parcels_div|safe }}
                        </div>


                    </div>
                </div>
            </div>
        </div>

    </div>
</div>



{% endblock %}

data/templates/data/ownners_list.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

{% block content %}
{% include 'main_nav.html' %}


<div class="my-4 shadow rounded p-4 bg-white">
    <div class="alert alert-primary">
        <strong>Records:</strong> {{ num_owners|default:"No"|apnumber|capfirst }} parcel owners{{ num_controls|pluralize }}
    </div>

    <ol class="list-group list-group-numbered">
        {% for owner in ownners_list %}
            <li class="list-group-item">{{ owner }}</li>
        {% empty %}
            <h5>No owners yet</h5>
        {% endfor %}
    </ol>
</div>



{% endblock %}

data/templates/data/parcel_detail.html
{% extends 'base.html' %}
{% load static %}

{% block meta_assets %}
    
{% endblock %}

{% block content %}
{% include 'main_nav.html' %}

<link rel="stylesheet" href="{% static 'css/open_layers_css.css' %}" />


<style>
    #shapefile_preview_map{width:100%;height:720px;}
</style>

<div class="p-4 my-4 bg-white">

    <div class="p-4 px-2 mb-4 bg-white">
        <p class="h5 text-dark text-center p-3 mb-3">{{ parcel.parcel_number }}</p>

        <div class="row">
            <div class="col-md-9">
              <div id="shapefile_preview_map"></div>
            </div>
            <div class="col bg-light shadow">
              <div id="detail_content" class="p-2">
                <p class="">FR Datum: {{ parcel.fr_datum }}</p>
                <p class="">County: {{ parcel.county }}</p>
                <p class="">Subcounty: {{ parcel.sub_county }}</p>
                <p class="">Land use: {{ parcel.land_use }}</p>
                <p class="">Hold type: {{ parcel.hold_type }}</p>
                <p class="">Date Surveyed: {{ parcel.date_created }}</p>

                {% if parcel.owners.all %}
                
                <p class='fs-6 fw-light lh-1'>Parcel owner(s):</p>
                <ol class="list-group list-group-numbered">'
                {% for owner in parcel.owners %}
                    <li class="list-group-item">{{ owner }}</li>
                {% endfor %}
                </ol>

                {% else %}
                    <p class="h6">No owner(s) listed for this parcel</p>
                {% endif %}

              </div>
            </div>
          </div>

            <script>
                const parcel_geojson = '{{ parcel_geojson|escapejs }}'
            </script>

          <script src="{% static 'data/js/parcel_detail_map.js' %}"></script>
    </div>
    
</div>


{% endblock %}

data/templates/data/parcels_write.html
{% extends 'base.html' %}
{% load static %}

{% block meta_assets %}
    
{% endblock %}

{% block content %}
{% include 'main_nav.html' %}

<link rel="stylesheet" href="{% static 'css/open_layers_css.css' %}" />


<style>
    #shapefile_preview_map{width:100%;height:520px;}
</style>

<div class="p-4 my-4 bg-white">

    <div class="shadow-sm py-4 px-2 mb-4 bg-white">

        {% if existing_parcels_geojson %}
        <p class="h5 text-success mb-3">Existing Parcels</p>

        <div class="row">
            <div class="col-md-9">
              <div id="shapefile_preview_map"></div>
            </div>
            <div class="col bg-light">
              <div id="detail_content" class="p-2"></div>
            </div>
          </div>

            <script>
                const existing_parcels_geojson = '{{ existing_parcels_geojson|escapejs }}'
            </script>

          <script src="{% static 'data/js/existing_parcels_map.js' %}"></script>
          {% else %}

          <p class="h5 text-dark mb-2">No Existing Parcels</p>

          {% endif %}
    </div>

    <form action="" method="post" id="parcel_form" enctype="multipart/form-data">
        <div class="shadow-sm py-4 px-2 mb-4 bg-white">
            <p class="py-3">Upload shapefile for updating database records</p>

            <div class="table-responsive">
                <table class="table table-light">
                    
                    {% csrf_token %}
                    {{ parcels_upload_form.as_table }}
                        
                </table>
            </div>

            <div class="my-2">
                
                <button type='submit' id="read_data_btn" class="btn btn-outline-success">
                    Upload
                </button>

            </div>
        </div>
    </form>
    
</div>


{% endblock %}

data/templates/data/sign_up.html
{% extends 'base.html' %} {% block content %}

{% include 'main_nav.html' %}

<div class="my-4">
    <div class="shadow rounded p-4 bg-white">

        <p class="h5 py-4 font-montserrat-medium">
            Enter Valid Credentials to create an account
        </p>

        <p class="font-montserrat-medium">
            Already have an account?
            <a class="inline-link font-montserrat-light" href="{% url 'login' %}">
                login
            </a>
        </p>
    
        <div class="py-2 px-5">
            <div class="">
                <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
            
                {{ signup_form.email.errors }}
                <div class="form-floating my-2">
                    {{ signup_form.email }}
                    <label for="id_email">{{ signup_form.email.label }}</label>
                </div>
            
                {{ signup_form.full_name.errors }}
                <div class="form-floating my-2">
                    {{ signup_form.full_name }}
                    <label for="id_full_name">{{ signup_form.full_name.label }}</label>
                </div>

                {{ signup_form.thumbnail_img.errors }}
                <div class="form-floating my-2">
                    {{ signup_form.thumbnail_img }}
                    <label for="id_full_name">{{ signup_form.thumbnail_img.label }}</label>
                </div>
            
                
                {{ signup_form.password2.errors }}
                <div class="form-floating my-2">
                    {{ signup_form.password1 }}
                    <label for="id_password1">{{ signup_form.password1.label }}</label>
                </div>
                
                <div class="form-floating my-2">
                    {{ signup_form.password2 }}
                    <label for="id_password2">{{ signup_form.password2.label }}</label>
                </div>
    
                <div class="d-grid gap-2 d-md-flex justify-content-md-center my-4">
                    <button type="submit" class="btn btn-info">Signup</button>
                </div>
                
                </form>
            </div>
    
        </div>
        
    </div>

</div>



{% endblock %}