cadastre/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from data.views import LoginUserView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/login/', LoginUserView.as_view(), name='login'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('data.urls')),
]

urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

data/urls.py
from django.urls import path

from .views import (
    HomeView,
    
    ReadParcelsView,
    WritenParcelsView,

    ReadControlsView,
    WritenControlsView,

    SignUpView,
    UserProfileView,

    OwnersListView,

    SearchView,

    ParcelDetailView,
    # ControlDetailView,

)

app_name = 'data'


urlpatterns = [
    path('', HomeView.as_view(), name='home_page'),
    
    path('parcels/', ReadParcelsView.as_view(), name='read_parcels_page'),
    path('writen-parcels/', WritenParcelsView.as_view(), name='writen_parcels_page'),

    path('controls/', ReadControlsView.as_view(), name='read_controls_page'),
    path('writen-controls/', WritenControlsView.as_view(), name='writen_controls_page'),

    path('parcel-owners/', OwnersListView.as_view(), name='owners_page'),

    path('sign-up/', SignUpView.as_view(), name='user_signup_page'),
    path('profile/', UserProfileView.as_view(), name='user_profile_page'),

    path('search', SearchView.as_view(), name='search_page'),

    path('parcel/<str:pk>/', ParcelDetailView.as_view(), name='parcel_page')
    # path('control/<int:pk>/', ControlDetailView.as_view(), name='control_page'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="shortcut icon" href="{% static 'favicon_io/favicon.ico' %}" type="image/x-icon">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicon_io/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon_io/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon_io/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'favicon_io/site.webmanifest' %}">

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'icons/bootstrap/bootstrap-icons.css' %}"/>

    <link rel="stylesheet" href="{% static 'css/cadastre-style.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/font-style.css' %}"/>

    {% block title %}
        {% if page_title %}
            <title>{{ page_title }} | Land Management System</title>
        {% else %}
            <title>Land Management System</title>
        {% endif %}
    {% endblock %}
    
    
</head>

<body>

    <div class="container-sm rubik-regular-font">
        {% block content %}{% endblock %}
    </div>
    
    <script src="{% static 'js/cadastre-utilities.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

templates/main_nav.html
<div class="mt-2 font-barlow-medium">
    <nav class="navbar navbar-expand-lg navbar-light bg-light rounded-3">
        <div class="container-fluid">
            <p class="navbar-brand mt-3">LADM-Data</p>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'data:home_page' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'data:read_parcels_page' %}">Parcels</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'data:read_controls_page' %}">Controls</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'data:user_signup_page' %}">Users</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'data:owners_page' %}">Owners</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'data:search_page' %}">Search</a>
                </li>
                </ul>
            </div>
        </div>
      </nav>
</div>